name: contribution_search
channels:
  - conda-forge
  - defaults
dependencies:
  - lxml
  - pathlib
  - pandas
  - panel
  - pip
  - pre-commit
  - requests
  - pip:
    - python-dotenv
    - pytest
    - pytest-cov
